### ISSUE TITLE
Training data count

### ISSUE THREAD

**Issue by spiderhands** [lengstrom/fast-style-transfer#154]
Hi! i am new to machine learning and especially to neural networks and tensorflow.
Does this network train on 1 image or there should be a lot of images in training folder?

**Comment by jontsanders** [comment]
The readme suggests to train against the MS COCO dataset. Coincidentally last night I did a tally of the number of files in the dataset and got 82,782. The dataset is quite large (13G) and I had a difficult time downloading all of it over HTTP (the link is in the readme). If, like me, you have trouble downloading the whole thing over HTTP, I found a torrent of the same dataset: http://academictorrents.com/details/f993c01f3c268b5d57219a38f8ec73ee7524421a

**Comment by jontsanders** [comment]
The README implies that you'd want to be using the MS COCO dataset, or something like it. That has about 82,000 images.

Since you're new, here's a couple things about that dataset I learned the hard way. First of all if you have trouble with downloading very large files (13GiB or so) over HTTP, a torrent is available: http://academictorrents.com/details/f993c01f3c268b5d57219a38f8ec73ee7524421a

Second, apparently there is a corrupt image in the dataset that can crash training cycles. I lost about 5 hours to a wasted training cycle already. See https://github.com/lengstrom/fast-style-transfer/issues/54#issuecomment-282981386 and for a command to find more corrupted images see https://github.com/lengstrom/fast-style-transfer/issues/54#issuecomment-306077181
