### ISSUE TITLE
got map has no len error when training

### ISSUE THREAD

**Issue by hifar** [lengstrom/fast-style-transfer#48]
D:\Python35\fast-style-transfer>python style.py --style style\4154001_72-48.jpg
--checkpoint-dir check --test in/IMG_1132_s.JPG --test-dir test
Traceback (most recent call last):
  File "style.py", line 166, in <module>
    main()
  File "style.py", line 146, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src\optimize.py", line 18, in optimize
    mod = len(content_targets) % batch_size
TypeError: object of type 'map' has no len()

**Comment by fbcotter** [comment]
I was having the same issue. I'm guessing you closed it after you figured out it was a python3 issue - map returns iterables in python3 rather than list. You can get around it by wrapping the return value of _get_files with a `list()` function in style.py:

    def _get_files(img_dir):
        files = list_files(img_dir)
        # return map(lambda x: os.path.join(img_dir,x), files)
        return list(map(lambda x: os.path.join(img_dir,x), files))

Or even better would be

    return [os.path.join(img_dir,x) for x in files]

Note that if you're using python 3, you'll also have to replace calls to `reduce()` in src/optimize.py with `functools.reduce()`

This post describes the changes for `map()`, `reduce()` and `filter()`:
http://stackoverflow.com/a/13638960/6437741

**Comment by lengstrom** [comment]
Pull requests welcome!
