### ISSUE TITLE
Training is slow on Tesla K80

### ISSUE THREAD

**Issue by LCLL** [lengstrom/fast-style-transfer#62]
Thanks for sharing the code.
As the document says "Training takes 4-6 hours on a Maxwell Titan X." I use Tesla K80 for training. However, it needs about 11 hour to complete the training process. I wonder if i miss some import tricks for training, can you give me some suggestions? Thank you.

My command is:
python style.py --style examples/style/rain_princess.jpg --checkpoint-dir checkpoint3/ --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 20

**Comment by luke14free** [comment]
I have been using a K80 as well and it's much slower than a Titan X or a GTX1080. One of the reasons is that the clock rate of the K80 is only 0.8Ghz while the Titan X and the GTX1080 have a clock rate of almost twice as much. With a GTX080 you need to use smaller batches (20 wont fit in memory since it has only 8GB of RAM), but it takes only ~1h50m per epoch so in your case (two epochs by default) it would take less than 4 hrs to train
