### ISSUE TITLE
No checkpoints after training finishes

### ISSUE THREAD

**Issue by Mechandrius** [lengstrom/fast-style-transfer#78]
When the training finishes, there are no checkpoint files created (the training only takes 5 seconds)

python style.py --style examples/style/myimage.jpg --checkpoint-dir examples/checkpoints --test examples/test/testimage.jpg --test-dir examples/test --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 20

I use the above command and myimage.jpg and testimage.jpg are images ... i also use the imagenet-vgg-verydeep-19 model.

What could be the cause of that?

**Comment by lymanzhang** [comment]
I encountered the same situation, no checkpoint files can be created after training.
python style.py --style ./styleImages/ScottNaismith.jpg --checkpoint-dir ./checkpoints --test ./testImages/lina.jpg --test-dir ./testImages --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 20

There must be something wrong with me...

**Comment by innominate817** [comment]
I just finished working through this same issue. 
- The 5 second training time suggests that the train2014 dataset is not actually being accessed (training will take several hours). Open the style.py file and double check that `TRAIN_PATH` (line 19) is assigned the correct directory path. It might be that it is `TRAIN_PATH = '/input/train2014'` when it should be `TRAIN_PATH = '/input/train2014/train2014'` due to the unzipping process.
- Tensorflow's Saver class seems to have been updated since the release of this project. To address this, I changed line 136 in /src/optimize.py from `saver = tf.train.Saver()` to `saver = tf.train.Saver(write_version=tf.train.SaverDef.V1)`. This will use the older Saver class.

Additional Notes: I believe the `--batch-size 20` in the example was intended for a Maxwell Titan X (12 GB). Unless you are running on comparable hardware you will need to use a lower batch size. You will know if you need to because you will get an out of memory error. For reference I am using a gtx 1070 (8 GB) and set my batch size to 12.

**Comment by dage** [comment]
Same problem here. After some debugging I found that my problem was that I had less images in the training folder than my batch size, so the following code in optimize.py removed my whole training set: https://github.com/lengstrom/fast-style-transfer/blob/master/src/optimize.py#L22

**Comment by darkmarthur** [comment]
@dage 

Which batch size you used?
